"""initial migration

Revision ID: 83928a15d003
Revises: 
Create Date: 2021-02-28 01:32:22.055190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83928a15d003'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tanks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('lat', sa.String(length=50), nullable=False),
    sa.Column('long', sa.String(length=50), nullable=False),
    sa.Column('percentage_full', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tanks')
    # ### end Alembic commands ###
